# Generated by Django 4.0.6 on 2022-07-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
