# Generated by Django 4.0.6 on 2022-07-17 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
