# Generated by Django 4.0.6 on 2022-07-17 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('date', models.DateField(default=datetime.date(2022, 7, 17), primary_key=True, serialize=False)),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
