# Generated by Django 4.0.6 on 2022-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalPrice',
            field=models.IntegerField(default=2500),
        ),
    ]
